### ISSUE TITLE
Unable to use Plugin

### ISSUE THREAD

**Issue by LukasSchulz** [SpikeTings/Mermaid#1]
I was able to install the Plugin in Mattermost, but I can't find any documentation on how to use it. 
I tried making a preformatted block like with latex but that doesn't work.
Could you please help me use this plugin?

**Comment by joebordes** [comment]
Hi

This plugin expects to receive a message from outside MM with the payload of the markdown. Something like this:

```
 'response_type' => 'in_channel',
 'attachments' => array(array(
	'color' => getMMMsgColor('blue'),
	'title' => $q['title'],
)),
'props' => array('mermaidData'=>markdown here),
```

we are using it from a chatbot

the chartjs plugin is the same:

```
'response_type' => 'in_channel',
'attachments' => array(array(
	'color' => getMMMsgColor('blue'),
	'title' => $q['title'],
)),
'props' => array('chartdata'=>chartjs data here)),
```

we are doing this from [coreBOS](https://github.com/tsolucio/corebos) with [this extension](https://github.com/tsolucio/chatwithme)

HTH

**Comment by LukasSchulz** [comment]
This helps a lot, thank you!

**Comment by iamkhalidbashir** [comment]
Still unclear how to use it

**Comment by pwamly** [comment]
> Still unclear how to use it

Hello,

kindly follow the following steps to test the plugin if you successfully installed it.


In Mattermost, go to Product menu > Integrations > Incoming Webhook.
        If you don’t have the Integrations option, incoming webhooks may not be enabled on your Mattermost server or may be disabled for non-admins. They can be enabled by a System Admin from System Console > Integrations > Integration Management. Once incoming webhooks are enabled, continue with the steps below.

1. Select Add Incoming Webhook and add a name and description for the webhook. The description can be up to 500 characters.

2. Select the channel to receive webhook payloads, then select Add to create the webhook.You will end up with a webhook endpoint that looks like so: (https://your-mattermost-server.com/hooks/xxx-generatedkey-xxx)

Note: Treat this endpoint as a secret. Anyone who has it will be able to post messages to your Mattermost instance.

3. Now Use the obtained endpoint(https://your-mattermost-server.com/hooks/xxx-generatedkey-xxx) to send a payload with http Post request. See the below sample payload as sent from postman.

```JSON
{
  "response_type": "in_channel",
  "attachments": [
    {
      "color": "red",
      "title": "Demo Bot"
    }
  ],
  "props": {
    "mermaidData": "graph TD;\n  A[Start] --> B[Process 3];\n  B --> C[Process 4];\n  C --> D[End];"
  }
}
```
